### ISSUE TITLE
Original License Headers missing

### ISSUE THREAD

**Issue by fabpot** [pagekit/razr#1]
I'm sure this is an oversight but as far as I can see, all license headers from PHP files coming from Twig were removed. This is against the original Twig License: https://github.com/fabpot/Twig/blob/master/LICENSE

Can you please fix this?

Thanks.

**Comment by steffans** [comment]
Sure, i would add this to copyright tag to all the class headers. Should i also include a link to your Twig repo on github or homepage ?

```
/**
 * @copyright Copyright (c) 2009-2014 by the Twig Team
 */
```
